### ISSUE TITLE
recommendation when including in python module

### ISSUE THREAD

**Issue by fkgruber** [Wainberg/ryp#5]
Hi
If I would like to include ryp in some python module how do you recommend to check and install R requirements? I assume the R is already installed in the system but there is no guarantees that the required R packages will be there already.

Is there a way that during the python module installation the R packages are also installed if needed?

thanks
F

**Comment by Wainberg** [comment]
ryp's only required R dependency is `arrow`. Its optional R dependencies are `Matrix` for sparse matrix support and `svglite` for inline plotting in Jupyter notebooks. 

The ryp conda package includes `r-arrow` as a dependency, but deliberately does not include the other two because they are only used in limited situations that a majority of users will not encounter. pip does not allow R packages as dependencies so the user has to install them manually if installing ryp through pip.

Fortunately, ryp checks that each R dependency is installed when it is about to be used. I just pushed some changes to make this happen in a consistent way across the three dependencies.
